const REALTIME_MESSAGE_TYPES = Object.freeze({
  WELCOME: 'WELCOME',
  AUTH_ERROR: 'AUTH_ERROR',
  SUBSCRIBE: 'SUBSCRIBE',
  SUBSCRIBED: 'SUBSCRIBED',
  UNSUBSCRIBE: 'UNSUBSCRIBE',
  UNSUBSCRIBED: 'UNSUBSCRIBED',
  EVENT: 'EVENT',
  ERROR: 'ERROR',
  PING: 'PING',
  PONG: 'PONG',
  RESUME: 'RESUME',
  RESUME_ACK: 'RESUME_ACK',
  REPLAY_REQUEST: 'REPLAY_REQUEST',
  REPLAY_ACK: 'REPLAY_ACK'
});

module.exports = { REALTIME_MESSAGE_TYPES };
