export const TelemetryEventType = Object.freeze({
  CONTEST_DETECTED: 'CONTEST_DETECTED',
  SESSION_STARTED: 'SESSION_STARTED',
  SESSION_ENDED: 'SESSION_ENDED',
  SESSION_RECOVERED: 'SESSION_RECOVERED',
  SESSION_PAUSED: 'SESSION_PAUSED',
  SESSION_RESUMED: 'SESSION_RESUMED',
  PROBLEM_OPENED: 'PROBLEM_OPENED',
  PROBLEM_SWITCHED: 'PROBLEM_SWITCHED',
  PAGE_RELOADED: 'PAGE_RELOADED',
  PAGE_EXITED: 'PAGE_EXITED',
  TAB_HIDDEN: 'TAB_HIDDEN',
  TAB_VISIBLE: 'TAB_VISIBLE',
  TAB_CLOSED: 'TAB_CLOSED',
  COLLECTOR_ERROR: 'COLLECTOR_ERROR'
});
